name: Deploy My Eerie Estate Dwell

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo apt update
          
          if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            
            if ! command -v node &> /dev/null; then
              sudo apt-get install -y nodejs npm
            fi
          fi
          
          if ! command -v npm &> /dev/null; then
            sudo apt-get install -y npm
          fi
          
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi
          
          sudo mkdir -p /opt/webapps
          sudo chown $USER:$USER /opt/webapps
          
          sudo mkdir -p /var/log/pm2
          sudo chown $USER:$USER /var/log/pm2
          
          if [ ! -d "/opt/webapps/my-eerie-estate-dwell" ]; then
            cd /opt/webapps
            git clone https://github.com/${{ github.repository }}.git my-eerie-estate-dwell
          else
            cd /opt/webapps/my-eerie-estate-dwell
            git fetch origin
            git reset --hard origin/main
          fi
          
          cd /opt/webapps/my-eerie-estate-dwell
          npm install --production
          
          if [ ! -f "ecosystem.config.js" ]; then
            cat > ecosystem.config.js << 'EOF'
          module.exports = {
            apps: [{
              name: 'my-eerie-estate-dwell',
              script: 'server.js',
              cwd: '/opt/webapps/my-eerie-estate-dwell',
              instances: 1,
              exec_mode: 'fork',
              env: {
                NODE_ENV: 'production',
                PORT: 3001
              },
              error_file: '/var/log/pm2/eerie-estate-error.log',
              out_file: '/var/log/pm2/eerie-estate-out.log',
              log_file: '/var/log/pm2/eerie-estate.log',
              time: true
            }]
          }
          EOF
          fi
          
          if pm2 list | grep -q "my-eerie-estate-dwell"; then
            pm2 restart my-eerie-estate-dwell
          else
            pm2 start ecosystem.config.js
          fi
          
          pm2 save
          
          if ! systemctl is-enabled pm2-$USER &> /dev/null; then
            pm2 startup systemd -u $USER --hp $HOME
            sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u $USER --hp $HOME
          fi
          
          echo "🎮 My Eerie Estate Dwell успешно развернуто!"
          echo "📱 Приложение доступно на порту 3001"